### PR TITLE
Fix deprecations

### LINKED ISSUE #2: Package.getStylesheetsPath is deprecated.
Store package style sheets in the `styles/` directory instead of `stylesheets/` in the `scratch` package
```
Package.getStylesheetsPath (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:460:9)
Package.getStylesheetPaths (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:471:32)
Package.loadStylesheets (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:453:38)
<unknown> (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:183:19)
Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:163:15)
Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:177:12)
```

### PR DESCRIPTION
**Pull request by kankaristo**
Fix deprecations reported by Deprecation Cop.

This fixes #2 and #3.

It seems that #1 is already fixed in `master`, but unpublished?

### CODE REVIEW

**Comment by kankaristo** [comment]
Now also fixes https://github.com/destradax/scratch/issues/5.

Ping @destradax.

**Comment by aioue** [comment]
+1

**Comment by destradax** [comment]
Hi! sorry for the delay guys, will merge tonight!

**Comment by destradax** [comment]
Fixed and published in version 0.3.1

**Pull request merged**
